//
//  CppAbseil.h
//  CppAbseil
//
//  Created by Undo Hatsune on 2024/01/16.
//

#import <Foundation/Foundation.h>

//! Project version number for CppAbseil.
FOUNDATION_EXPORT double CppAbseilVersionNumber;

//! Project version string for CppAbseil.
FOUNDATION_EXPORT const unsigned char CppAbseilVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <CppAbseil/PublicHeader.h>


#import <CppAbseil/absl_algorithm_algorithm.hpp>
#import <CppAbseil/absl_algorithm_container.hpp>
#import <CppAbseil/absl_base_attributes.hpp>
#import <CppAbseil/absl_base_call_once.hpp>
#import <CppAbseil/absl_base_casts.hpp>
#import <CppAbseil/absl_base_config.hpp>
#import <CppAbseil/absl_base_const_init.hpp>
#import <CppAbseil/absl_base_dynamic_annotations.hpp>
#import <CppAbseil/absl_base_internal_atomic_hook.hpp>
#import <CppAbseil/absl_base_internal_cycleclock.hpp>
#import <CppAbseil/absl_base_internal_cycleclock_config.hpp>
#import <CppAbseil/absl_base_internal_direct_mmap.hpp>
#import <CppAbseil/absl_base_internal_dynamic_annotations.hpp>
#import <CppAbseil/absl_base_internal_endian.hpp>
#import <CppAbseil/absl_base_internal_errno_saver.hpp>
#import <CppAbseil/absl_base_internal_fast_type_id.hpp>
#import <CppAbseil/absl_base_internal_hide_ptr.hpp>
#import <CppAbseil/absl_base_internal_identity.hpp>
#import <CppAbseil/absl_base_internal_inline_variable.hpp>
#import <CppAbseil/absl_base_internal_invoke.hpp>
#import <CppAbseil/absl_base_internal_low_level_alloc.hpp>
#import <CppAbseil/absl_base_internal_low_level_scheduling.hpp>
#import <CppAbseil/absl_base_internal_per_thread_tls.hpp>
#import <CppAbseil/absl_base_internal_raw_logging.hpp>
#import <CppAbseil/absl_base_internal_scheduling_mode.hpp>
#import <CppAbseil/absl_base_internal_spinlock.hpp>
#import <CppAbseil/absl_base_internal_spinlock_wait.hpp>
#import <CppAbseil/absl_base_internal_strerror.hpp>
#import <CppAbseil/absl_base_internal_sysinfo.hpp>
#import <CppAbseil/absl_base_internal_thread_annotations.hpp>
#import <CppAbseil/absl_base_internal_thread_identity.hpp>
#import <CppAbseil/absl_base_internal_throw_delegate.hpp>
#import <CppAbseil/absl_base_internal_tsan_mutex_interface.hpp>
#import <CppAbseil/absl_base_internal_unaligned_access.hpp>
#import <CppAbseil/absl_base_internal_unscaledcycleclock.hpp>
#import <CppAbseil/absl_base_internal_unscaledcycleclock_config.hpp>
#import <CppAbseil/absl_base_log_severity.hpp>
#import <CppAbseil/absl_base_macros.hpp>
#import <CppAbseil/absl_base_optimization.hpp>
#import <CppAbseil/absl_base_options.hpp>
#import <CppAbseil/absl_base_policy_checks.hpp>
#import <CppAbseil/absl_base_port.hpp>
#import <CppAbseil/absl_base_prefetch.hpp>
#import <CppAbseil/absl_base_thread_annotations.hpp>
#import <CppAbseil/absl_cleanup_cleanup.hpp>
#import <CppAbseil/absl_cleanup_internal_cleanup.hpp>
#import <CppAbseil/absl_container_btree_map.hpp>
#import <CppAbseil/absl_container_btree_set.hpp>
#import <CppAbseil/absl_container_fixed_array.hpp>
#import <CppAbseil/absl_container_flat_hash_map.hpp>
#import <CppAbseil/absl_container_flat_hash_set.hpp>
#import <CppAbseil/absl_container_inlined_vector.hpp>
#import <CppAbseil/absl_container_internal_btree.hpp>
#import <CppAbseil/absl_container_internal_btree_container.hpp>
#import <CppAbseil/absl_container_internal_common.hpp>
#import <CppAbseil/absl_container_internal_common_policy_traits.hpp>
#import <CppAbseil/absl_container_internal_compressed_tuple.hpp>
#import <CppAbseil/absl_container_internal_container_memory.hpp>
#import <CppAbseil/absl_container_internal_hash_function_defaults.hpp>
#import <CppAbseil/absl_container_internal_hash_policy_traits.hpp>
#import <CppAbseil/absl_container_internal_hashtable_debug_hooks.hpp>
#import <CppAbseil/absl_container_internal_hashtablez_sampler.hpp>
#import <CppAbseil/absl_container_internal_inlined_vector.hpp>
#import <CppAbseil/absl_container_internal_layout.hpp>
#import <CppAbseil/absl_container_internal_node_slot_policy.hpp>
#import <CppAbseil/absl_container_internal_raw_hash_map.hpp>
#import <CppAbseil/absl_container_internal_raw_hash_set.hpp>
#import <CppAbseil/absl_container_node_hash_map.hpp>
#import <CppAbseil/absl_container_node_hash_set.hpp>
#import <CppAbseil/absl_crc_crc32c.hpp>
#import <CppAbseil/absl_crc_internal_cpu_detect.hpp>
#import <CppAbseil/absl_crc_internal_crc.hpp>
#import <CppAbseil/absl_crc_internal_crc32_x86_arm_combined_simd.hpp>
#import <CppAbseil/absl_crc_internal_crc32c.hpp>
#import <CppAbseil/absl_crc_internal_crc32c_inline.hpp>
#import <CppAbseil/absl_crc_internal_crc_cord_state.hpp>
#import <CppAbseil/absl_crc_internal_crc_internal.hpp>
#import <CppAbseil/absl_crc_internal_crc_memcpy.hpp>
#import <CppAbseil/absl_debugging_internal_address_is_readable.hpp>
#import <CppAbseil/absl_debugging_internal_demangle.hpp>
#import <CppAbseil/absl_debugging_internal_elf_mem_image.hpp>
#import <CppAbseil/absl_debugging_internal_examine_stack.hpp>
#import <CppAbseil/absl_debugging_internal_stacktrace_config.hpp>
#import <CppAbseil/absl_debugging_internal_symbolize.hpp>
#import <CppAbseil/absl_debugging_internal_vdso_support.hpp>
#import <CppAbseil/absl_debugging_stacktrace.hpp>
#import <CppAbseil/absl_debugging_symbolize.hpp>
#import <CppAbseil/absl_functional_any_invocable.hpp>
#import <CppAbseil/absl_functional_function_ref.hpp>
#import <CppAbseil/absl_functional_internal_any_invocable.hpp>
#import <CppAbseil/absl_functional_internal_function_ref.hpp>
#import <CppAbseil/absl_hash_hash.hpp>
#import <CppAbseil/absl_hash_internal_city.hpp>
#import <CppAbseil/absl_hash_internal_hash.hpp>
#import <CppAbseil/absl_hash_internal_low_level_hash.hpp>
#import <CppAbseil/absl_log_absl_check.hpp>
#import <CppAbseil/absl_log_absl_log.hpp>
#import <CppAbseil/absl_log_die_if_null.hpp>
#import <CppAbseil/absl_log_globals.hpp>
#import <CppAbseil/absl_log_initialize.hpp>
#import <CppAbseil/absl_log_internal_append_truncated.hpp>
#import <CppAbseil/absl_log_internal_check_impl.hpp>
#import <CppAbseil/absl_log_internal_check_op.hpp>
#import <CppAbseil/absl_log_internal_conditions.hpp>
#import <CppAbseil/absl_log_internal_config.hpp>
#import <CppAbseil/absl_log_internal_globals.hpp>
#import <CppAbseil/absl_log_internal_log_format.hpp>
#import <CppAbseil/absl_log_internal_log_impl.hpp>
#import <CppAbseil/absl_log_internal_log_message.hpp>
#import <CppAbseil/absl_log_internal_log_sink_set.hpp>
#import <CppAbseil/absl_log_internal_nullguard.hpp>
#import <CppAbseil/absl_log_internal_nullstream.hpp>
#import <CppAbseil/absl_log_internal_proto.hpp>
#import <CppAbseil/absl_log_internal_strip.hpp>
#import <CppAbseil/absl_log_internal_voidify.hpp>
#import <CppAbseil/absl_log_log.hpp>
#import <CppAbseil/absl_log_log_entry.hpp>
#import <CppAbseil/absl_log_log_sink.hpp>
#import <CppAbseil/absl_log_log_sink_registry.hpp>
#import <CppAbseil/absl_memory_memory.hpp>
#import <CppAbseil/absl_meta_type_traits.hpp>
#import <CppAbseil/absl_numeric_bits.hpp>
#import <CppAbseil/absl_numeric_int128.hpp>
#import <CppAbseil/absl_numeric_internal_bits.hpp>
#import <CppAbseil/absl_numeric_internal_representation.hpp>
#import <CppAbseil/absl_profiling_internal_exponential_biased.hpp>
#import <CppAbseil/absl_profiling_internal_sample_recorder.hpp>
#import <CppAbseil/absl_random_bernoulli_distribution.hpp>
#import <CppAbseil/absl_random_beta_distribution.hpp>
#import <CppAbseil/absl_random_distributions.hpp>
#import <CppAbseil/absl_random_exponential_distribution.hpp>
#import <CppAbseil/absl_random_gaussian_distribution.hpp>
#import <CppAbseil/absl_random_internal_distribution_caller.hpp>
#import <CppAbseil/absl_random_internal_fast_uniform_bits.hpp>
#import <CppAbseil/absl_random_internal_fastmath.hpp>
#import <CppAbseil/absl_random_internal_generate_real.hpp>
#import <CppAbseil/absl_random_internal_iostream_state_saver.hpp>
#import <CppAbseil/absl_random_internal_nonsecure_base.hpp>
#import <CppAbseil/absl_random_internal_pcg_engine.hpp>
#import <CppAbseil/absl_random_internal_platform.hpp>
#import <CppAbseil/absl_random_internal_pool_urbg.hpp>
#import <CppAbseil/absl_random_internal_randen.hpp>
#import <CppAbseil/absl_random_internal_randen_detect.hpp>
#import <CppAbseil/absl_random_internal_randen_engine.hpp>
#import <CppAbseil/absl_random_internal_randen_hwaes.hpp>
#import <CppAbseil/absl_random_internal_randen_slow.hpp>
#import <CppAbseil/absl_random_internal_randen_traits.hpp>
#import <CppAbseil/absl_random_internal_salted_seed_seq.hpp>
#import <CppAbseil/absl_random_internal_seed_material.hpp>
#import <CppAbseil/absl_random_internal_traits.hpp>
#import <CppAbseil/absl_random_internal_uniform_helper.hpp>
#import <CppAbseil/absl_random_internal_wide_multiply.hpp>
#import <CppAbseil/absl_random_log_uniform_int_distribution.hpp>
#import <CppAbseil/absl_random_poisson_distribution.hpp>
#import <CppAbseil/absl_random_random.hpp>
#import <CppAbseil/absl_random_seed_gen_exception.hpp>
#import <CppAbseil/absl_random_seed_sequences.hpp>
#import <CppAbseil/absl_random_uniform_int_distribution.hpp>
#import <CppAbseil/absl_random_uniform_real_distribution.hpp>
#import <CppAbseil/absl_random_zipf_distribution.hpp>
#import <CppAbseil/absl_status_internal_status_internal.hpp>
#import <CppAbseil/absl_status_internal_statusor_internal.hpp>
#import <CppAbseil/absl_status_status.hpp>
#import <CppAbseil/absl_status_status_payload_printer.hpp>
#import <CppAbseil/absl_status_statusor.hpp>
#import <CppAbseil/absl_strings_ascii.hpp>
#import <CppAbseil/absl_strings_charconv.hpp>
#import <CppAbseil/absl_strings_cord.hpp>
#import <CppAbseil/absl_strings_cord_analysis.hpp>
#import <CppAbseil/absl_strings_cord_buffer.hpp>
#import <CppAbseil/absl_strings_escaping.hpp>
#import <CppAbseil/absl_strings_internal_char_map.hpp>
#import <CppAbseil/absl_strings_internal_charconv_bigint.hpp>
#import <CppAbseil/absl_strings_internal_charconv_parse.hpp>
#import <CppAbseil/absl_strings_internal_cord_data_edge.hpp>
#import <CppAbseil/absl_strings_internal_cord_internal.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_btree.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_btree_navigator.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_btree_reader.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_consume.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_crc.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_flat.hpp>
#import <CppAbseil/absl_strings_internal_cord_rep_ring.hpp>
#import <CppAbseil/absl_strings_internal_cordz_functions.hpp>
#import <CppAbseil/absl_strings_internal_cordz_handle.hpp>
#import <CppAbseil/absl_strings_internal_cordz_info.hpp>
#import <CppAbseil/absl_strings_internal_cordz_statistics.hpp>
#import <CppAbseil/absl_strings_internal_cordz_update_scope.hpp>
#import <CppAbseil/absl_strings_internal_cordz_update_tracker.hpp>
#import <CppAbseil/absl_strings_internal_escaping.hpp>
#import <CppAbseil/absl_strings_internal_has_absl_stringify.hpp>
#import <CppAbseil/absl_strings_internal_memutil.hpp>
#import <CppAbseil/absl_strings_internal_ostringstream.hpp>
#import <CppAbseil/absl_strings_internal_resize_uninitialized.hpp>
#import <CppAbseil/absl_strings_internal_stl_type_traits.hpp>
#import <CppAbseil/absl_strings_internal_str_format_arg.hpp>
#import <CppAbseil/absl_strings_internal_str_format_bind.hpp>
#import <CppAbseil/absl_strings_internal_str_format_checker.hpp>
#import <CppAbseil/absl_strings_internal_str_format_constexpr_parser.hpp>
#import <CppAbseil/absl_strings_internal_str_format_extension.hpp>
#import <CppAbseil/absl_strings_internal_str_format_float_conversion.hpp>
#import <CppAbseil/absl_strings_internal_str_format_output.hpp>
#import <CppAbseil/absl_strings_internal_str_format_parser.hpp>
#import <CppAbseil/absl_strings_internal_str_join_internal.hpp>
#import <CppAbseil/absl_strings_internal_str_split_internal.hpp>
#import <CppAbseil/absl_strings_internal_string_constant.hpp>
#import <CppAbseil/absl_strings_internal_stringify_sink.hpp>
#import <CppAbseil/absl_strings_internal_utf8.hpp>
#import <CppAbseil/absl_strings_match.hpp>
#import <CppAbseil/absl_strings_numbers.hpp>
#import <CppAbseil/absl_strings_str_cat.hpp>
#import <CppAbseil/absl_strings_str_format.hpp>
#import <CppAbseil/absl_strings_str_join.hpp>
#import <CppAbseil/absl_strings_str_replace.hpp>
#import <CppAbseil/absl_strings_str_split.hpp>
#import <CppAbseil/absl_strings_string_view.hpp>
#import <CppAbseil/absl_strings_strip.hpp>
#import <CppAbseil/absl_strings_substitute.hpp>
#import <CppAbseil/absl_synchronization_internal_create_thread_identity.hpp>
#import <CppAbseil/absl_synchronization_internal_futex.hpp>
#import <CppAbseil/absl_synchronization_internal_futex_waiter.hpp>
#import <CppAbseil/absl_synchronization_internal_graphcycles.hpp>
#import <CppAbseil/absl_synchronization_internal_kernel_timeout.hpp>
#import <CppAbseil/absl_synchronization_internal_per_thread_sem.hpp>
#import <CppAbseil/absl_synchronization_internal_pthread_waiter.hpp>
#import <CppAbseil/absl_synchronization_internal_sem_waiter.hpp>
#import <CppAbseil/absl_synchronization_internal_stdcpp_waiter.hpp>
#import <CppAbseil/absl_synchronization_internal_waiter.hpp>
#import <CppAbseil/absl_synchronization_internal_waiter_base.hpp>
#import <CppAbseil/absl_synchronization_internal_win32_waiter.hpp>
#import <CppAbseil/absl_synchronization_mutex.hpp>
#import <CppAbseil/absl_time_civil_time.hpp>
#import <CppAbseil/absl_time_clock.hpp>
#import <CppAbseil/absl_time_internal_cctz_include_cctz_civil_time.hpp>
#import <CppAbseil/absl_time_internal_cctz_include_cctz_civil_time_detail.hpp>
#import <CppAbseil/absl_time_internal_cctz_include_cctz_time_zone.hpp>
#import <CppAbseil/absl_time_internal_cctz_include_cctz_zone_info_source.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_time_zone_fixed.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_time_zone_if.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_time_zone_impl.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_time_zone_info.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_time_zone_libc.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_time_zone_posix.hpp>
#import <CppAbseil/absl_time_internal_cctz_src_tzfile.hpp>
#import <CppAbseil/absl_time_time.hpp>
#import <CppAbseil/absl_types_any.hpp>
#import <CppAbseil/absl_types_bad_any_cast.hpp>
#import <CppAbseil/absl_types_bad_optional_access.hpp>
#import <CppAbseil/absl_types_bad_variant_access.hpp>
#import <CppAbseil/absl_types_compare.hpp>
#import <CppAbseil/absl_types_internal_optional.hpp>
#import <CppAbseil/absl_types_internal_span.hpp>
#import <CppAbseil/absl_types_internal_variant.hpp>
#import <CppAbseil/absl_types_optional.hpp>
#import <CppAbseil/absl_types_span.hpp>
#import <CppAbseil/absl_types_variant.hpp>
#import <CppAbseil/absl_utility_utility.hpp>
